model_hidden_dim: 256
model_num_layers: 3
model_dropout_prob: 0.2
max_train_episodes: 350
learning_rate: 0.001
gamma: 0.98
buffer_size: 100000
epsilon_min: 0.02
epsilon_max: 1.0
epsilon_decay_period: 21000
batch_size: 64
update_target_freq: 100